DEPP 432 Assignment 10

In [9]:
import numpy as np
import pandas as pd
np.random.seed(seed=42)

This utitlity function top_n
    takes d dictionary and n = count of key value pairs to return after sorting as parameters
    embedded function keyfunction(k) returns value for key k
    initializes empty key_list and value_list
    for loop cycles through the top n values in sorted values
        appends the key to the key list
        appends the value to the value list
    returns the key_list and value_list

In [10]:
def top_n(d, n):
    def keyfunction(k):
        return d[k]
    key_list = []
    value_list = []
    for key in sorted(d, key=keyfunction, reverse=False)[:n]:
        key_list.append(key)
        value_list.append(d[key])
    return key_list, value_list

This function knn_50
    takes k with default 3 value as parameters
        representing k = number of nearest neighbors to be collected per shopper
    creates a random 2D array with shape 50, 5 representing 
        50 shoppers
        5 binary choices for grocery items
    completes the 50, 5 via numpy random function selecting either 0 or 1 with random seed = 42
    creates a pandas dataframe object with that 50,5 array
    inserts a column identifying the 50 shoppers by row
    creates empty lists to contain lists 
        knn = contains lists of closest n neightbors for each of 50 neighbors 
        dist = same list but contains distances to the closest n neighbors for 50 neighbors
    cycles through the each of 50 shopper rows via for loop
        for each row, 
            an 1,5 array 'dude' is initialized with the values from that row.
            an empty dictionary 'neighbors' is defined
        a separate for for loop cycles through the 50 rows again
            for each row, a 1,5 array 'dudes_neighbor' is initialized with values from that row.
            calculates the L2 euclidian distance between dude and dudes_neighbor
                via numpy's linalg.norm function
                rounds to the nearest 5
            assigns key = 'dudesneighbor' with the value 'L2' distance
                dude and dudesneighbor are index values 0 to 50, thus dictionary keys are +1
            calls top_n with neighbors dictionary and number of top neighbors to return

In [11]:
def knn_50(k=3):
    buy_bin = np.random.choice([0, 1], size=(50,5))
    buy_bin_df = pd.DataFrame(buy_bin, columns =['Eggs','Bread','Milk','Butter','Soda'])
    shopper_count = 50
    shopper = range(1,shopper_count+1)
    buy_bin_df.insert(0, 'Shopper', shopper, True) 
    knn=[]
    dist=[]
    for neighbor_1 in range(shopper_count):
        dude = buy_bin_df.iloc[neighbor_1, 1:].values
        neighbors = {}
        for neighbor_2 in range(shopper_count):
            dudes_neighbor = buy_bin_df.iloc[neighbor_2, 1:].values
            L2 = round(np.linalg.norm(dude-dudes_neighbor),5)
            neighbors[neighbor_2+1]=L2
            knn_list, knn_dist = top_n(neighbors,k)
        knn.append(knn_list)
        dist.append(knn_dist)
    knn, dist
    buy_bin_df.insert(6, 'knn', knn, True) 
    buy_bin_df.insert(7, 'dist', dist, True)
    return buy_bin_df

In [12]:
buy_bin_df = knn_50(4)
buy_bin_df

,Shopper,Eggs,Bread,Milk,Butter,Soda,knn,dist
0,1,0,1,0,0,0,"[1, 8, 11, 12]","[0.0, 0.0, 1.0, 1.0]"
1,2,1,0,0,0,1,"[2, 3, 27, 30]","[0.0, 1.0, 1.0, 1.0]"
2,3,0,0,0,0,1,"[3, 30, 2, 13]","[0.0, 0.0, 1.0, 1.0]"
3,4,0,1,1,1,0,"[4, 42, 11, 17]","[0.0, 0.0, 1.0, 1.0]"
4,5,1,0,1,1,1,"[5, 29, 6, 7]","[0.0, 0.0, 1.0, 1.0]"
5,6,1,1,1,1,1,"[6, 19, 47, 5]","[0.0, 0.0, 0.0, 1.0]"
6,7,0,0,1,1,1,"[7, 9, 33, 45]","[0.0, 0.0, 0.0, 0.0]"
7,8,0,1,0,0,0,"[1, 8, 11, 12]","[0.0, 0.0, 1.0, 1.0]"
8,9,0,0,1,1,1,"[7, 9, 33, 45]","[0.0, 0.0, 0.0, 0.0]"
9,10,1,1,0,1,1,"[10, 14, 26, 6]","[0.0, 0.0, 0.0, 1.0]"
10,11,0,1,0,1,0,"[11, 17, 44, 1]","[0.0, 0.0, 0.0, 1.0]"
11,12,1,1,0,0,0,"[12, 1, 8, 15]","[0.0, 1.0, 1.0, 1.0]"
12,13,0,0,0,0,0,"[13, 28, 31, 39]","[0.0, 0.0, 0.0, 0.0]"
13,14,1,1,0,1,1,"[10, 14, 26, 6]","[0.0, 0.0, 0.0, 1.0]"
14,15,1,1,0,1,0,"[15, 10, 11, 12]","[0.0, 1.0, 1.0, 1.0]"
15,16,1,1,1,0,1,"[16, 48, 6, 19]","[0.0, 0.0, 1.0, 1.0]"
16,17,0,1,0,1,0,"[11, 17, 44, 1]","[0.0, 0.0, 0.0, 1.0]"
17,18,0,1,0,1,1,"[18, 10, 11, 14]","[0.0, 1.0, 1.0, 1.0]"
18,19,1,1,1,1,1,"[6, 19, 47, 5]","[0.0, 0.0, 0.0, 1.0]"
19,20,1,1,1,1,0,"[20, 22, 4, 6]","[0.0, 0.0, 1.0, 1.0]"
20,21,0,1,1,1,1,"[21, 4, 6, 7]","[0.0, 1.0, 1.0, 1.0]"
21,22,1,1,1,1,0,"[20, 22, 4, 6]","[0.0, 0.0, 1.0, 1.0]"
22,23,1,0,1,1,0,"[23, 24, 5, 20]","[0.0, 0.0, 1.0, 1.0]"
23,24,1,0,1,1,0,"[23, 24, 5, 20]","[0.0, 0.0, 1.0, 1.0]"
24,25,1,0,1,0,0,"[25, 46, 49, 23]","[0.0, 0.0, 0.0, 1.0]"
25,26,1,1,0,1,1,"[10, 14, 26, 6]","[0.0, 0.0, 0.0, 1.0]"
26,27,1,0,0,0,0,"[27, 36, 50, 2]","[0.0, 0.0, 0.0, 1.0]"
27,28,0,0,0,0,0,"[13, 28, 31, 39]","[0.0, 0.0, 0.0, 0.0]"
28,29,1,0,1,1,1,"[5, 29, 6, 7]","[0.0, 0.0, 1.0, 1.0]"
29,30,0,0,0,0,1,"[3, 30, 2, 13]","[0.0, 0.0, 1.0, 1.0]"
30,31,0,0,0,0,0,"[13, 28, 31, 39]","[0.0, 0.0, 0.0, 0.0]"
31,32,1,0,1,0,1,"[32, 2, 5, 16]","[0.0, 1.0, 1.0, 1.0]"
32,33,0,0,1,1,1,"[7, 9, 33, 45]","[0.0, 0.0, 0.0, 0.0]"
33,34,0,1,0,0,1,"[34, 38, 41, 1]","[0.0, 0.0, 0.0, 1.0]"
34,35,1,0,0,1,1,"[35, 2, 5, 10]","[0.0, 1.0, 1.0, 1.0]"
35,36,1,0,0,0,0,"[27, 36, 50, 2]","[0.0, 0.0, 0.0, 1.0]"
36,37,0,0,1,0,0,"[37, 13, 25, 28]","[0.0, 1.0, 1.0, 1.0]"
37,38,0,1,0,0,1,"[34, 38, 41, 1]","[0.0, 0.0, 0.0, 1.0]"
38,39,0,0,0,0,0,"[13, 28, 31, 39]","[0.0, 0.0, 0.0, 0.0]"
39,40,1,1,1,0,0,"[40, 12, 16, 20]","[0.0, 1.0, 1.0, 1.0]"
40,41,0,1,0,0,1,"[34, 38, 41, 1]","[0.0, 0.0, 0.0, 1.0]"
41,42,0,1,1,1,0,"[4, 42, 11, 17]","[0.0, 0.0, 1.0, 1.0]"
42,43,0,0,0,0,0,"[13, 28, 31, 39]","[0.0, 0.0, 0.0, 0.0]"
43,44,0,1,0,1,0,"[11, 17, 44, 1]","[0.0, 0.0, 0.0, 1.0]"
44,45,0,0,1,1,1,"[7, 9, 33, 45]","[0.0, 0.0, 0.0, 0.0]"
45,46,1,0,1,0,0,"[25, 46, 49, 23]","[0.0, 0.0, 0.0, 1.0]"
46,47,1,1,1,1,1,"[6, 19, 47, 5]","[0.0, 0.0, 0.0, 1.0]"
47,48,1,1,1,0,1,"[16, 48, 6, 19]","[0.0, 0.0, 1.0, 1.0]"
48,49,1,0,1,0,0,"[25, 46, 49, 23]","[0.0, 0.0, 0.0, 1.0]"
49,50,1,0,0,0,0,"[27, 36, 50, 2]","[0.0, 0.0, 0.0, 1.0]"

The time to compute knn is related to (1) shoppers^2 for computing neighbors (2) shoppers*k*2 for time to sort the dictionary of 50 = shoppers computed distances and append k items to 2 lists.  Sorting is via dictionary method.  So let's say O(shoppers^2 + shoppers*k*2) is big O time for computation.  From the timed experiment below, one can see that processing time is relatively insensitive to the number of neighbors selected.

In [21]:
import time
elapsed=[]
for k in range(1,11):
    start = time.time()
    knn_50(k)
    end = time.time()
    print(end-start,k)
    elapsed.append(end-start)

0.5533838272094727 1
0.5146932601928711 2
0.5199177265167236 3
0.5271539688110352 4
0.5289511680603027 5
0.5278031826019287 6
0.5339691638946533 7
0.5235278606414795 8
0.5303912162780762 9
0.527214765548706 10